version: '3.7'

services:
    nginx:
        image: nginx
        ports:
            - 8181:80
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./:/usr/share/nginx/html
